# -*- coding: utf-8 -*-
"""Scrap image from Pixabay

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Xez7zG8WGBp9MOa18DgAidt2msEjL0G
"""

import requests
import os

api_key = '35428194-f806941a429b19ee5838722ec'
keyword = input("Enter Your Keyword").replace(' ','+')
url = f'https://pixabay.com/api/?key={api_key}&q={keyword}&image_type=photo' #PIXBAY api

resposne = requests.get(url)
image_data = resposne.json()
hits = image_data.get('hits')

image_id=1
for hit in hits:
    image_url = hit.get('webformatURL')
    image_response = requests.get(image_url)
    if image_response.status_code == 200:
        image_name = keyword.replace('+','-')
        with open(f'{image_name}_{image_id}.jpg','wb') as file:
            file.write(image_response.content)
            image_id+=1
            print(f'{image_name}_{image_id-1}.jpg downloaded')